### ISSUE TITLE
Updates from Milestone 1

### ISSUE THREAD

**Issue by meagangardner** [UBC-MDS/dsci_522_group3#39]
Please feel free to add in other checklist items we are missing
- [x] update README file link to: https://ubc-mds.github.io/customer-term-deposits-predictor/analysis/customer-term-deposits-predictor.html 
    - I have changed our github pages to "root" so we can specify the html file in the analysis folder specifically
    - COMPLETED BY: Meagan
- [x] delete doc folder
    - this won't be necessary now that we have updated github pages to root
    - COMPLETED BY: Meagan
- [ ] update license file 
    - Milestone 1 feedback: No Creative Commons License (for project report) was specified
    - We are missing a license (see Tiffany's github for an example). 
- [x] Breaking the golden rule
    - Milestone 1 feedback: "did EDA before splitting which can lead to data leakage"
    - COMPLETED BY: Elshaday
- [x] Code of conduct 
    - Milestone 1 feedback: "Email under "enforcement" should be tied to the team"
    - COMPLETED BY: Meagan
- [x] Github issues for communication
    - Milestone 1 feedback: Github issues were rarely used for project communication
