### ISSUE TITLE
Peer Review/Milestone 1 Feedback Checklist

### ISSUE THREAD

**Issue by meagangardner** [UBC-MDS/dsci_522_group3#54]
- [x] Update README file instructions
    - Feedback note: "README instructions with header [How to Run the Data Analysis](https://github.com/UBC-MDS/customer-term-deposits-predictor#how-to-run-the-data-analysis): Generally, great job on outlining the steps. However, point 3 and 4 are a bit misleading. These two points should describe alternative methods for running the analysis but due to the documentation they currently reflect sequential steps. As the user it seems that I am to run the analysis twice first using the "Run All Cells..." in the notebook and next through the terminal. Clarifying these steps will help ensure users understand that they can choose either method."
    - Note: This will need to be updated anyway with the Makefile instructions so we can wait until that is complete to fix this!
    - **Updated with new make file instructions (can provide link to last commit if needed)**
- [x] Fix download_customer_data.py script to include clear distinct path names and documentation
    - "Script attribute naming convention: Improve the naming of attributes passed to the script download_customer_data.py. Currently, the attribute names are not descriptive enough, as they only list different paths. Replace these generic names with more descriptive ones to better indicate their purpose."
    - Evidence: Link to commit message [here](https://github.com/UBC-MDS/customer-term-deposits-predictor/commit/fa8277624052bf961079ae27e1818e323ca72932)
- [x] No Creative Commons License
    - Missing Creative Commons License: include the creative commons license in your License. (see Tiffany's [github](https://github.com/ttimbers/breast-cancer-predictor/blob/3.0.0/LICENSE) for an example). 
- [x] Include Script descriptions in README file
    - It might be helpful to include a brief description at the beginning of each script in the README file.
    - Updated README with makefile instructions
- [x] Add function docstrings
    - Adding docstrings for each function would make the code easier to understand and use.
    - Done! Can provide link to src file if needed
- [x] Error handling:
    - Consider adding checks for common issues in scripts, such as missing input files or directories.
    - Handled during tests for functions. Can provide link to test file if needed.
- [x] Correlation heatmap filename:
    - "The filename for the correlation heatmap plot currently doesn't align with its content (e.g., "feature_densities_by_class.png"). Updating it to something like "correlation_heatmap.png" would improve clarity and help others quickly identify the file's content."
    - We believe the name is well selected.
- [x] README validate.py
    - "README instructions doesn't run validate.py. A person who is trying to reproduce this analysis should run the same validation to ensure input data is correct."
    - Our Validate.py got incorporated into the preprocessed script for Milestone 4 for readability, so is no longer necessary for it's own script.
- [x] Code flow
    -  Good feedback but unfortunately doesn't seem feasible given our time constraints
    - "Data is split in split_data.py and then recombined again in fit_logistic_regression.py to do correlation check on the input data. The flow of the code could be better if the correlation check was done in validate.py before the data gets split."
    - This was a conscious decision made to help with our analysis.
- [x] Quarto Render issues in Dockerfile:
    - "Wasn't able to render to report using the container environment."
    - *Please follow the readme instructions strictly to activate the environment within the DockerFile. Details provided in the README file - can provide link if needed

**Comment by meagangardner** [comment]
see changelog for specific details on completion: https://github.com/UBC-MDS/customer-term-deposits-predictor/blob/main/CHANGELOG.md
